name: Build Zigbee Firmware
on:
  workflow_call:
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          # Legacy versions: v1 and v2
          - chip: esp32c6
            model: moax
            defines: '-DGALOPED_AXIS=1'
          - chip: esp32c6
            model: biax
            defines: '-DGALOPED_AXIS=2'
          - chip: esp32c6
            model: co2
            defines: '-DGALOPED_AXIS=2 -DGALOPED_CLIMATE=1 -DGALOPED_CO2=1'
    container:
      image: espressif/idf:release-v6.0
      options: -u 2025:2025
    name: Firmware Zigbee ${{ matrix.chip }} - ${{ matrix.model }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/.cache/ccache
          key: idf-zigbee-${{ matrix.chip }}
      - name: Build ${{ matrix.chip }}
        shell: bash
        working-directory: firmware-zigbee/galoped
        run: |
            source /opt/esp/idf/export.sh
            idf.py build
            idf.py merge-bin -o galoped-zigbee-firmware-${{ matrix.chip }}-${{ matrix.model }}.bin
            ccache -s
        env:
          IDF_TARGET: ${{ matrix.chip }}
          IDF_CCACHE_ENABLE: "1"
          CCACHE_DIR: ${{ github.workspace }}/.cache/ccache
          TERM: xterm-256color
          CLICOLOR_FORCE: "1"
          FORCE_COLOR: "1"
          PY_COLORS: "1"
          CMAKE_COLOR_DIAGNOSTICS: "ON"
      - name: Archive firmware file
        uses: actions/upload-artifact@v7
        with:
          name: galoped-zigbee-firmware-${{ matrix.chip }}-${{ matrix.model }}.bin
          path: firmware-zigbee/galoped/build/galoped-zigbee-firmware-*.bin
