# Workflow to (re)build firmware files
name: ESP-IDF CI
on:
  push:
    paths:
      - '.github/workflows/ci-idf.yaml'
      - 'bin/build.sh'
      - 'firmware-wifi/**'
    branches:
      - '*'
  pull_request:
    paths:
      - '.github/workflows/ci-idf.yaml'
      - 'bin/build.sh'
      - 'firmware-*/**'
    branches:
      - '*'
jobs:
  build-firmware:
    uses: ./.github/workflows/build-firmware-zigbee.yaml
    secrets: inherit # pass all secrets

