# Workflow to (re)build firmware files
name: ESP-IDF CI
on:
  push:
    paths:
      - '.github/workflows/ci-idf.yaml'
      - '.github/workflows/build-firmware-zigbee.yaml'
      - 'bin/build.sh'
      - 'firmware-zigbee/**'
    branches:
      - '*'
  pull_request:
    paths:
      - '.github/workflows/ci-idf.yaml'
      - 'bin/build.sh'
      - 'firmware-zigbee/**'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware-zigbee:
    uses: ./.github/workflows/build-firmware-zigbee.yaml
    secrets: inherit # pass all secrets

