# Workflow to (re)build firmware files
name: PlatformIO CI
on:
  push:
    paths:
      - '.github/workflows/ci-pio.yaml'
      - '.github/workflows/build-firmware-wifi.yaml'
      - 'bin/build.sh'
      - 'firmware-wifi/**'
    branches:
      - '*'
  pull_request:
    paths:
      - '.github/workflows/ci-pio.yaml'
      - 'bin/build.sh'
      - 'firmware-wifi/**'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware-wifi:
    uses: ./.github/workflows/build-firmware-wifi.yaml
    secrets: inherit # pass all secrets
