name: PlatformIO CI
on:
  push:
    paths:
      - '.github/workflows/pio-ci.yaml'
      - 'bin/build.sh'
      - 'firmware-*/**'
    branches:
      - master
      - Version-2
  pull_request:
    paths:
      - '.github/workflows/pio-ci.yaml'
      - 'bin/build.sh'
      - 'firmware-*/**'
    branches:
      - master
jobs:
  user-manual:
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/latex:v1
      options: -u 2025:2025
    steps:
      - uses: actions/checkout@v4
      - name: Build manual
        run: |
            echo "::group::latex build"
            # See Dockerfile for static environment
            export CI=true
            cd manual
            xelatex manual.tex
            xelatex manual.tex
            xelatex manual.tex
            echo "::endgroup::"
      - name: Archive manual file
        uses: actions/upload-artifact@v4
        with:
          name: user-manual
          path: manual/manual.pdf

  build-firmware:
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/platformio:v4
      options: -u 2025:2025
    strategy:
      matrix:
        include:
          # Legacy versions: v1 and v2
          - chip: esp32
            model: rgb
          - chip: esp32
            model: retro
          - chip: esp32
            model: biax
          # Galoped-s
          - chip: esp32c6
            model: biax
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ matrix.chip }}
      - name: Build firmware
        run: |
            echo "::group::pio ci"
            # See Dockerfile for static environment
            export CI=true
            # Define FW version
            export PLATFORMIO_BUILD_FLAGS="-DGALOPED_VERSION=${{ steps.vars.outputs.sha_short }}"
            # Build for each model
            ./bin/build.sh ${{ matrix.chip }} ${{ matrix.model }}
            echo "::endgroup::"
      - name: Archive firmware file
        uses: actions/upload-artifact@v4
        with:
          name: firmware-wifi-${{ matrix.chip }}-${{ matrix.model }}
          path: firmware-wifi/galoped-*.bin
  build-autoexec:
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/platformio:v4
      options: -u 2025:2025
    strategy:
      matrix:
        model: ['linear', 'logf']
    steps:
      - uses: actions/checkout@v4
      - name: Build autoexec.be
        run: |
            # Build autoexec for each variant (Linear and Logf)
            ./bin/mk-autoexec.py -t autoexec.be --scale ${{ matrix.model }} -o autoexec.be
      - name: Archive firmware file
        uses: actions/upload-artifact@v4
        with:
          name: autoexec-${{ matrix.model }}
          path: autoexec.be
