# Workflow to (re)build firmware files
name: PlatformIO CI
on:
  push:
    paths:
      - '.github/workflows/pio-ci.yaml'
      - 'bin/build.sh'
      - 'firmware-*/**'
    branches:
      - '*'
  pull_request:
    paths:
      - '.github/workflows/pio-ci.yaml'
      - 'bin/build.sh'
      - 'firmware-*/**'
    branches:
      - '*'
jobs:
  build-firmware:
    uses: ./.github/workflows/build-firmware.yaml

