name: Release

on:
  push:
    branches:
      - 'Release-*'
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-firmware:
    uses: ./.github/workflows/build-firmware.yaml
    secrets: inherit # pass all secrets
  build-release:
    needs: build-firmware
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/platformio:v4
      options: -u 2025:2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Release commit message
        # Dump commit message as RN title
        run: |
          mkdir -p rss/files
          echo ${{ github.sha }} > rss/files/version.txt
          git show -s --format=%B > rss/rn.txt
      - name: Fetch built artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: firmware-wifi-*
          # If true, the downloaded artifacts will be in the same directory specified by path.
          merge-multiple: true
          path: rss/files
      - name: Release test
        # Dump commit message as RN title
        run: |
          cd rss
          ls -lah
          cd files
          ls -lah
      - name: Release
        uses: softprops/action-gh-release@v3
        # if: github.ref_type == 'tag'
        with:
          draft: true
          body_path: rss/rn.txt
          files: rss/files/*
